spring:
  application:
    name: spring-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: ENC(cIz4QKupDvxjWg8C+g3YCH/y36SKFNCg)
    username: ENC(w0lHVSLgGbFAceCtOheTdQ==)
    password: ENC(N5jRJj61sBPkq+kU9T4jBQ==)
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      platform: h2
      mode: always
      schema-locations: classpath:/schema.sql
      data-locations: classpath:/data.sql
  profiles:
    include: jwt

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: devgrr
    algorithm: PBEWithMD5AndDES

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    net.devgrr.springdemo: debug

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
server:
  port: 8080