CREATE TABLE IF NOT EXISTS `member`
(
    id            bigint generated by default as identity,
    user_id       varchar(255)          not null unique,
    password      varchar(255)          not null,
    email         varchar(255)          not null unique,
    name          varchar(255)          not null,
    role          enum ('ADMIN','USER') not null default 'USER',
    refresh_token varchar(1000),
    created_at    timestamp(6),
    updated_at    timestamp(6),
    primary key (id)
);